brew:
  enable_update: false
  enable_upgrade: false
  add_repositories:
  - homebrew/cask-versions
  - homebrew/cask-fonts
  install_packages:
    - mas 
    - fish
    - vim
    - tmux
    - git
    - wget
    - tree
    - thefuck
    # - mask
    - openssl
    - docker-compose
    - terraform
    - curl
    - ffmpeg
    - tree
    - hub
    - tig
    - jq
    - peco
    - rust
    - node
    - yarn
  install_apps:
    - alfred
    - google-chrome
    - iterm2
    - google-japanese-ime
    - github
    - docker
    - intellij-idea
    - android-studio
    - zoomus
    - visual-studio-code
    - sourcetree
    - psequel
    - vlc
    - karabiner-elements
    - font-hackgen
    - visualvm
    - wireshark
    - gimp
    - sequel-pro-nightly
    - clipy
    - cyberduck
    - discord
  install_apps_from_store:
    - Microsoft\ Excel
    - Focus
    - Numbers
    - Microsoft PowerPoint
    - 1Password\ 7
    - Pages
    - Keynote
    - LINE
    - Magnet
    - Microsoft\ Word
    - Kindle
    - Slack
sdkman:
  - java
  - dotty
  - gradle
  - groovy
  - kotlin
  - sbt
  - scala
