brew:
  enable_update: false
  enable_upgrade: false
  add_repositories:
  - homebrew/cask-versions
  - homebrew/cask-fonts
  install_packages:
    - mas 
    - fish
    - vim
    - tmux
    - git
    - wget
    - tree
    - thefuck
    # - mask
    - openssl
    - docker-compose
    - terraform
    - curl
    - ffmpeg
    - tree
    - hub
    - tig
    - jq
    - peco
    - rust
    - node
    - yarn
  install_apps:
    - alfred
    - google-chrome
    - iterm2
    - google-japanese-ime
    - github
    - docker
    - intellij-idea
    - android-studio
    - zoomus
    - visual-studio-code
    - sourcetree
    - psequel
    - vlc
    - karabiner-elements
    - font-hackgen
    - visualvm
    - wireshark
    - gimp
    - sequel-pro-nightly
    - clipy
    - cyberduck
    - discord
  install_apps_from_store:
    # Microsoft Excel
    - 462058435
    # Microsoft Word
    - 462054704
    # Microsoft PowerPoint
    - 462062816
    # Focus
    - 777233759
    # 1Password
    - 1333542190
    # Pages
    - 409201541
    # Keynote
    - 409183694
    # LINE
    - 539883307
    # Magnet
    - 441258766
    # Kindle
    - 405399194
    # Slack
    - 803453959
sdkman:
  - java
  - dotty
  - gradle
  - groovy
  - kotlin
  - sbt
  - scala
